# .github/workflows/deepseek-assist.yml
name: DeepSeek Code Assistant

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches: [main]

jobs:
  assist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Assistant
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: python src/main.py --event=${{ github.event_name }}
